🐛Corrección de detalles de historia 1
enflujo/imagina-vacs pull request #89
Opened 2023-08-18 17:50 UTC by anattolia

Estaban desacomodadas las columnas.

2023-08-18 21:23 UTC, 1cgonza requested changes

2023-08-18 21:23 UTC, 1cgonza commented on src/pages/proyecto1.astro
> +          >. Además, permite comparar los datos nacionales con los datos recogidos en los municipios <span>PDET</span>.
el `span` usado en `<span>PDET</span>` se necesita? ahí no parece estar haciendo nada

2023-08-18 21:56 UTC, anattolia commented on src/pages/proyecto1.astro
> +          >. Además, permite comparar los datos nacionales con los datos recogidos en los municipios <span>PDET</span>.
Eso es código viejo que hay que limpiar pero bueno, lo quito.

2023-08-22 21:57 UTC, anattolia commented
@1cgonza ahora? :)

2023-08-23 21:50 UTC, merged